/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as PendingReviewRouteImport } from './routes/pending-review'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile_.$id'
import { Route as ProfileSavedRouteImport } from './routes/profile.saved'
import { Route as ProfileListingsRouteImport } from './routes/profile.listings'
import { Route as PlacesNewRouteImport } from './routes/places.new'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as PlacesIdEditRouteImport } from './routes/places.$id.edit'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingReviewRoute = PendingReviewRouteImport.update({
  id: '/pending-review',
  path: '/pending-review',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile_/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileListingsRoute = ProfileListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ProfileRoute,
} as any)
const PlacesNewRoute = PlacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlacesRoute,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlacesRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdEditRoute = PlacesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PlacesIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-review': typeof PendingReviewRoute
  '/places': typeof PlacesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/chat/$id': typeof ChatIdRoute
  '/places/$id': typeof PlacesIdRouteWithChildren
  '/places/new': typeof PlacesNewRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/$id': typeof ProfileIdRoute
  '/places/$id/edit': typeof PlacesIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-review': typeof PendingReviewRoute
  '/places': typeof PlacesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/chat/$id': typeof ChatIdRoute
  '/places/$id': typeof PlacesIdRouteWithChildren
  '/places/new': typeof PlacesNewRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/$id': typeof ProfileIdRoute
  '/places/$id/edit': typeof PlacesIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-review': typeof PendingReviewRoute
  '/places': typeof PlacesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/chat/$id': typeof ChatIdRoute
  '/places/$id': typeof PlacesIdRouteWithChildren
  '/places/new': typeof PlacesNewRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile_/$id': typeof ProfileIdRoute
  '/places/$id/edit': typeof PlacesIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chats'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pending-review'
    | '/places'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/chat/$id'
    | '/places/$id'
    | '/places/new'
    | '/profile/listings'
    | '/profile/saved'
    | '/profile/$id'
    | '/places/$id/edit'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chats'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pending-review'
    | '/places'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/chat/$id'
    | '/places/$id'
    | '/places/new'
    | '/profile/listings'
    | '/profile/saved'
    | '/profile/$id'
    | '/places/$id/edit'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chats'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pending-review'
    | '/places'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/verify'
    | '/chat/$id'
    | '/places/$id'
    | '/places/new'
    | '/profile/listings'
    | '/profile/saved'
    | '/profile_/$id'
    | '/places/$id/edit'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatsRoute: typeof ChatsRoute
  DiscoverRoute: typeof DiscoverRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingReviewRoute: typeof PendingReviewRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  ChatIdRoute: typeof ChatIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-review': {
      id: '/pending-review'
      path: '/pending-review'
      fullPath: '/pending-review'
      preLoaderRoute: typeof PendingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$id': {
      id: '/profile_/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/saved': {
      id: '/profile/saved'
      path: '/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/listings': {
      id: '/profile/listings'
      path: '/listings'
      fullPath: '/profile/listings'
      preLoaderRoute: typeof ProfileListingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/places/new': {
      id: '/places/new'
      path: '/new'
      fullPath: '/places/new'
      preLoaderRoute: typeof PlacesNewRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id/edit': {
      id: '/places/$id/edit'
      path: '/edit'
      fullPath: '/places/$id/edit'
      preLoaderRoute: typeof PlacesIdEditRouteImport
      parentRoute: typeof PlacesIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlacesIdRouteChildren {
  PlacesIdEditRoute: typeof PlacesIdEditRoute
}

const PlacesIdRouteChildren: PlacesIdRouteChildren = {
  PlacesIdEditRoute: PlacesIdEditRoute,
}

const PlacesIdRouteWithChildren = PlacesIdRoute._addFileChildren(
  PlacesIdRouteChildren,
)

interface PlacesRouteChildren {
  PlacesIdRoute: typeof PlacesIdRouteWithChildren
  PlacesNewRoute: typeof PlacesNewRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesIdRoute: PlacesIdRouteWithChildren,
  PlacesNewRoute: PlacesNewRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

interface ProfileRouteChildren {
  ProfileListingsRoute: typeof ProfileListingsRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileListingsRoute: ProfileListingsRoute,
  ProfileSavedRoute: ProfileSavedRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatsRoute: ChatsRoute,
  DiscoverRoute: DiscoverRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  PendingReviewRoute: PendingReviewRoute,
  PlacesRoute: PlacesRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  ChatIdRoute: ChatIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
